version: '3.8'
services:
  data-reader-service:
    image: data-reader-service:latest
    build:
      context: ./services/DataReaderService
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./history.json:/app/history.json
    command: [ "java", "-jar", "/app/data-reader-service.jar", "/app/partial_history.json" ]

  # Space to add more services later (e.g. another-service: etc.)
